name: Composer Unused

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  composer-unused:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run composer-unused
        run: vendor/bin/composer-unused --no-interaction --ansi
