name: PHP Compatibility

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  php-compatibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer, phpcs

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPCompatibility
        run: vendor/bin/phpcs -p --standard=PHPCompatibility --runtime-set testVersion 8.1-8.4 src
